Repository uwblueprint/sistering, pull requests merged in 2022-05, with the labels that each got.

#296 Include Employee Info in POC Card
  backend/graphql/types/postingType.ts
  backend/services/implementations/postingService.ts
  backend/types.ts
  frontend/src/components/common/PostingDetails.tsx
  frontend/src/components/pages/admin/posting/AdminPostingDetails.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
  frontend/src/types/api/EmployeeTypes.ts
  frontend/src/types/api/PostingTypes.ts
Labels: ship it 🚢

#299 Add header to schedule review table
  frontend/src/components/admin/schedule/AdminScheduleTable.tsx
  frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
Labels: ship it 🚢

#301 Add volunteers and employees to seed data
  backend/graphql/index.ts
  backend/prisma/seed.ts
  frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
Labels: ship it 🚢

#302 Remove google login UI
  frontend/src/components/auth/Login.tsx
Labels: ship it 🚢

#277 Add submit signups volunteer avail client call
  backend/graphql/index.ts
  frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
  frontend/src/components/volunteer/shifts/VolunteerAvailabilityTable.tsx
  frontend/src/components/volunteer/shifts/VolunteerAvailabilityTableRow.tsx
  frontend/src/types/api/PostingTypes.ts
  frontend/src/types/api/ShiftTypes.ts
  frontend/src/types/api/SignupTypes.ts
Labels: ship it 🚢

#269 Implement monthly calendar header
  frontend/src/components/admin/ShiftCalendar/MonthViewShiftCalendar.tsx
  frontend/src/components/admin/ShiftCalendar/MonthlyViewReadOnlyShiftCalendar.tsx
  frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
  frontend/src/utils/DateTimeUtils.ts
Labels: ship it 🚢

#297 Validate against past dates in create posting form
  frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx
  frontend/src/components/admin/posting/CreatePostingShifts.tsx
Labels: ship it 🚢

#305 Resolve console warning on volunteer scheduling pages
  frontend/src/components/common/PostingDetails.tsx
  frontend/src/components/volunteer/PostingCard.tsx
Labels: ship it 🚢

#310 Add Logout Functionality to Navbar
  frontend/src/components/common/Navbar.tsx
Labels: ship it 🚢

#309 Update sitee favicon + title
  frontend/public/favicon.ico
  frontend/public/index.html
Labels: ship it 🚢

#308 Cleanup default page for admin
  frontend/src/components/pages/Default.tsx
Labels: ship it 🚢

#315 Check Role in Private Route
  frontend/src/App.tsx
  frontend/src/components/auth/PrivateRoute.tsx
  frontend/src/types/AuthTypes.ts
Labels: awaiting review 👀

#300 Exit edit mode when selecting a new shift time
  frontend/src/components/admin/schedule/AdminScheduleVolunteerTable.tsx
  frontend/src/components/admin/schedule/ScheduleSidePanel.tsx
  frontend/src/components/pages/admin/schedule/testData.ts
Labels: changes requested 📝

#317 Polish Admin Posting UI with sticky component
  frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx
  frontend/src/components/admin/posting/CreatePostingShifts.tsx
  frontend/src/components/common/SideNavbarWithTitle.tsx
  frontend/src/components/common/StickyBackNext.tsx
  frontend/src/components/pages/admin/posting/CreatePostingBasicInfoPage.tsx
  frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
  frontend/src/components/pages/admin/posting/CreatePostingShiftsPage.tsx
  frontend/src/theme/colors.ts
Labels: ship it 🚢

#319 Lena/admin schedule state management
  frontend/src/components/admin/schedule/AdminScheduleVolunteerRow.tsx
  frontend/src/components/admin/schedule/AdminScheduleVolunteerTable.tsx
  frontend/src/components/admin/schedule/ScheduleSidePanel.tsx
  frontend/src/components/admin/schedule/ShiftTimeHeader.tsx
  frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
  frontend/src/types/api/ShiftTypes.ts
  frontend/src/types/api/SignupTypes.ts
Labels: awaiting review 👀

#314 disable admin from creating multi-day shifts
  frontend/src/components/admin/ShiftCalendar/WeekViewShiftCalendar.tsx
  frontend/src/components/admin/posting/CreatePostingShifts.tsx
Labels: ship it 🚢

#318 Add Loading component + usages
  frontend/src/components/common/Loading.tsx
  frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
  frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx
Labels: ship it 🚢

#304 Update status when removing volunteer + use API data for table
  frontend/src/components/admin/RemoveVolunteerModal.tsx
  frontend/src/components/admin/ShiftCalendar/Calendar.css
  frontend/src/components/admin/ShiftCalendar/MonthViewShiftCalendar.tsx
  frontend/src/components/admin/ShiftCalendar/MonthlyViewReadOnlyShiftCalendar.tsx
  frontend/src/components/admin/schedule/AdminScheduleTable.tsx
  frontend/src/components/admin/schedule/AdminScheduleTableRow.tsx
  frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
  frontend/src/types/api/SignupTypes.ts
  frontend/src/utils/DateTimeUtils.ts
Labels: ship it 🚢

#320 Shifts table header feature
  frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx
  frontend/src/components/volunteer/shifts/VolunteerShiftsTable.tsx
  frontend/src/components/volunteer/shifts/VolunteerShiftsTableRow.tsx
  frontend/src/theme/index.ts
  frontend/src/types/api/ShiftSignupTypes.ts
  frontend/src/types/api/ShiftTypes.ts
Labels: ship it 🚢

#321 Fetch posting details in admin schedule page
  frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
  frontend/src/utils/DateTimeUtils.ts
Labels: ship it 🚢

#322 Prevent next when no skills or employees
  frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx
Labels: ship it 🚢

#325 Remove sign up button from login page
  frontend/src/components/auth/Login.tsx
Labels: awaiting review 👀

#326 Redirect to browse posting page from home page for volunteers
  frontend/src/components/pages/Default.tsx
Labels: ship it 🚢

#303 Add hotjar/GA integration for analytics
  frontend/package.json
  frontend/src/App.tsx
  frontend/yarn.lock
Labels: ship it 🚢

#349 create ui for admin schedule
  frontend/src/components/pages/Default.tsx
  frontend/src/components/volunteer/PostingCard.tsx
Labels: ship it 🚢

#350 Fix bad key for table row - react not updating properly
  frontend/src/components/volunteer/shifts/VolunteerAvailabilityTable.tsx
Labels: ship it 🚢

#358 Logout user when token is expired
  frontend/src/index.tsx
Labels: ship it 🚢

#363 Publish admin schedule
  frontend/src/components/admin/ShiftCalendar/MonthlyViewReadOnlyShiftCalendar.tsx
  frontend/src/components/admin/schedule/AdminScheduleTable.tsx
  frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
  frontend/src/types/api/SignupTypes.ts
Labels: ship it 🚢

#361 Fix My Shifts Table Links
  frontend/src/components/volunteer/shifts/VolunteerShiftsTable.tsx
  frontend/src/components/volunteer/shifts/VolunteerShiftsTableRow.tsx
Labels: ship it 🚢

#365 Implement Account Creation Header
  frontend/src/components/pages/NewAccountPage.tsx
Labels: ship it 🚢

#366 Generic Delete Modal (#347)
  frontend/src/components/admin/DeleteModal.tsx
Labels: ship it 🚢

#367 Create Account Landing Page
  frontend/src/App.tsx
  frontend/src/components/pages/CreateAccountPage.tsx
  frontend/src/constants/Routes.ts
Labels: ship it 🚢

#368 Create new route for account creation
  frontend/src/App.tsx
  frontend/src/constants/Routes.ts
Labels: ship it 🚢

#369 Fix initial month state for MonthViewShiftCalendar
  frontend/src/components/admin/ShiftCalendar/MonthViewShiftCalendar.tsx
Labels: awaiting review 👀

#370 Created password change successful page
  frontend/src/App.tsx
  frontend/src/components/auth/PasswordResetSuccess.tsx
  frontend/src/constants/Routes.ts
Labels: ship it 🚢

#374 Create Success Page
  frontend/src/App.tsx
  frontend/src/components/pages/AccountCreatedPage.tsx
  frontend/src/constants/Routes.ts
Labels: ship it 🚢

#371 Add eventClick to full calendar to open sidebar to shift
  frontend/src/components/admin/ShiftCalendar/MonthViewShiftCalendar.tsx
  frontend/src/components/admin/ShiftCalendar/MonthlyViewReadOnlyShiftCalendar.tsx
  frontend/src/components/admin/schedule/ScheduleSidePanel.tsx
  frontend/src/components/admin/schedule/ShiftTimeHeader.tsx
  frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
Labels: ship it 🚢

#373 Reset Password Page
  frontend/src/components/auth/ResetPassword.tsx
  frontend/src/components/pages/CreateAccountPage.tsx
Labels: ship it 🚢

#372 Create Email Sent Page
  frontend/src/components/auth/DoneResetPassword.tsx
Labels: ship it 🚢
