Repository uwblueprint/sistering, pull requests merged in 2022-07, with the labels that each got.

#450 Polish upcoming volunteer shifts table to match design
  frontend/src/components/volunteer/shifts/VolunteerPendingShiftsTableRow.tsx
  frontend/src/components/volunteer/shifts/VolunteerShiftsTable.tsx
  frontend/src/components/volunteer/shifts/VolunteerShiftsTableEmptyState.tsx
  frontend/src/components/volunteer/shifts/VolunteerUpcomingShiftsTable.tsx
  frontend/src/components/volunteer/shifts/VolunteerUpcomingShiftsTableRow.tsx
Labels: ship it 🚢

#459 Deduplicate postings in requests pending table
  frontend/src/components/volunteer/shifts/VolunteerPendingShiftsTableRow.tsx
  frontend/src/components/volunteer/shifts/VolunteerShiftsTable.tsx
Labels: ship it 🚢

#467 Updated InviteUser Model
  backend/prisma/migrations/20220705005839_remove_map_from_email_role_change_role_type_to_role/migration.sql
  backend/prisma/schema.prisma
Labels: awaiting review 👀

#462 Add conditions to render event vs regular postings on postin cards
  frontend/src/components/pages/Default.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
  frontend/src/components/volunteer/EmptyPostingCard.tsx
  frontend/src/components/volunteer/PostingCard.tsx
  frontend/src/types/PostingTypes.ts
  frontend/src/utils/DateTimeUtils.ts
Labels: ship it 🚢

#449 Creating user management side panel + branch selection menu
  frontend/src/components/pages/admin/user/AdminUserManagementPage.tsx
  frontend/src/components/pages/admin/user/MultiBranchSelector.tsx
  frontend/src/components/pages/admin/user/MultiUserDrawer.tsx
  frontend/src/components/pages/admin/user/ProfileDrawer.tsx
Labels: ship it 🚢

#465 Query skills and create languages array used for account creation page
  frontend/src/components/user/AccountForm.tsx
  frontend/src/types/api/SkillTypes.ts
  frontend/src/types/api/UserType.ts
Labels: ship it 🚢

#466 Employee Model Migration
  backend/graphql/types/userType.ts
  backend/prisma/migrations/20220702234302_make_branch_for_employee_users_an_array_of_branches/migration.sql
  backend/prisma/schema.prisma
  backend/prisma/seed.ts
  backend/services/implementations/userService.ts
  backend/types.ts
  frontend/src/components/pages/NewAccountPage.tsx
  frontend/src/components/user/AccountForm.tsx
  frontend/src/types/api/EmployeeTypes.ts
  frontend/src/types/api/UserType.ts
Labels: ship it 🚢

#446 Admin homepage posting card
  backend/graphql/types/postingType.ts
  backend/prisma/migrations/20220620220742_remove_archive_state_from_posting/migration.sql
  backend/prisma/schema.prisma
  backend/types.ts
  frontend/package.json
  frontend/src/components/admin/AdminPostingCard.tsx
  frontend/src/components/pages/Default.tsx
  frontend/src/components/volunteer/PostingCard.tsx
  frontend/src/types/PostingTypes.ts
  frontend/src/types/api/PostingTypes.ts
  frontend/src/utils/DateTimeUtils.ts
  frontend/yarn.lock
Labels: ship it 🚢

#464 Clean shift request type names
  backend/graphql/resolvers/postingResolvers.ts
  backend/services/implementations/shiftService.ts
  backend/services/interfaces/IShiftService.ts
  backend/services/interfaces/postingService.ts
  backend/types.ts
Labels: ship it 🚢

#470 437 create send user invite resolver
  backend/graphql/index.ts
  backend/graphql/resolvers/userResolvers.ts
  backend/graphql/types/userType.ts
  backend/services/implementations/userService.ts
  backend/services/interfaces/userService.ts
  backend/types.ts
Labels: ship it 🚢

#463 Remove employee title from schema
  backend/graphql/types/userType.ts
  backend/prisma/migrations/20220703014509_remove_employee_title_field/migration.sql
  backend/prisma/schema.prisma
  backend/prisma/seed.ts
  backend/services/implementations/userService.ts
  backend/types.ts
  frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx
  frontend/src/components/admin/posting/CreatePostingReview.tsx
  frontend/src/components/common/PocCard.tsx
  frontend/src/components/common/PostingDetails.tsx
  frontend/src/components/pages/admin/posting/AdminPostingDetails.tsx
  frontend/src/components/pages/admin/user/AdminUserManagementPage.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
  frontend/src/components/user/AccountForm.tsx
  frontend/src/types/api/EmployeeTypes.ts
  frontend/src/types/api/UserType.ts
Labels: ship it 🚢

#478 Add resolver and types for delete user invite
  backend/graphql/resolvers/userResolvers.ts
  backend/graphql/types/userType.ts
  backend/prisma/migrations/20220710175708_user_invite_better_field_name_unique_email/migration.sql
  backend/prisma/schema.prisma
  backend/services/implementations/userService.ts
  backend/services/interfaces/userService.ts
  backend/types.ts
Labels: ship it 🚢

#460 Remove signup resolvers
  backend/graphql/index.ts
  backend/graphql/resolvers/shiftSignupResolvers.ts
  backend/graphql/types/shiftSignupType.ts
  backend/middlewares/auth.ts
  backend/services/implementations/shiftSignupService.ts
  backend/services/interfaces/shiftSignupService.ts
  backend/types.ts
  frontend/src/components/admin/RemoveVolunteerModal.tsx
  frontend/src/components/admin/schedule/AdminScheduleTableRow.tsx
  frontend/src/components/auth/DoneResetPassword.tsx
Labels: ship it 🚢

#487 Integrate query data with admin homepage
  frontend/src/App.tsx
  frontend/src/components/admin/AdminHomepageHeader.tsx
  frontend/src/components/admin/BranchManagerModal.tsx
  frontend/src/components/admin/BranchManagerTable.tsx
  frontend/src/components/pages/admin/AdminHomepage.tsx
Labels: ship it 🚢

#488 Fix branches query to sort by id
  backend/services/implementations/branchService.ts
  frontend/src/components/admin/BranchManagerModal.tsx
Labels: ship it 🚢

#490 Add email template utils
  backend/constants/emailTemplates.ts
  backend/services/implementations/authService.ts
  backend/utilities/templateUtils.ts
Labels: ship it 🚢

#491 438-Send an Email along with creating the userInvite row
  backend/graphql/resolvers/userResolvers.ts
Labels: ship it 🚢

#496 Refactor admin create posting pages into single page component
  frontend/src/App.tsx
  frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx
  frontend/src/components/pages/admin/posting/CreatePostingBasicInfoPage.tsx
  frontend/src/components/pages/admin/posting/CreatePostingPage.tsx
  frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
  frontend/src/components/pages/admin/posting/CreatePostingShiftsPage.tsx
  frontend/src/components/pages/admin/user/AdminUserManagementPage.tsx
  frontend/src/constants/Routes.ts
Labels: ship it 🚢

#497 Admin User Management Page Header
  frontend/src/components/admin/AdminUserManagementPageHeader.tsx
  frontend/src/components/pages/admin/AdminHomepage.tsx
  frontend/src/components/pages/admin/user/AdminUserManagementPage.tsx
Labels: ship it 🚢

#499 Admin/Volunteer edit account form + Update seed data
  backend/prisma/seed.ts
  backend/services/implementations/userService.ts
  frontend/src/App.tsx
  frontend/src/components/pages/EditAccountPage.tsx
  frontend/src/components/pages/NewAccountPage.tsx
  frontend/src/components/user/AccountForm.tsx
  frontend/src/components/user/fields/SelectorField.tsx
  frontend/src/components/user/fields/TextField.tsx
  frontend/src/constants/Routes.ts
  frontend/src/types/api/LanguageTypes.ts
  frontend/src/types/api/UserType.ts
Labels: ship it 🚢

#508 Add success toast for adding users to branches
  frontend/src/components/pages/admin/user/AdminUserManagementPage.tsx
Labels: awaiting review 👀

#511 Pending invitations modal
  frontend/src/components/admin/AdminUserManagementPageHeader.tsx
  frontend/src/components/admin/UserInvitesModal.tsx
  frontend/src/components/admin/UserInvitesTable.tsx
  frontend/src/components/admin/schedule/AdminScheduleTableDate.tsx
  frontend/src/components/pages/admin/user/AdminUserManagementPage.tsx
  frontend/src/theme/index.ts
  frontend/src/types/api/UserInviteTypes.ts
  frontend/src/utils/DateTimeUtils.ts
Labels: awaiting review 👀, ship it 🚢

#494 Read only schedule details page
  backend/graphql/index.ts
  frontend/src/App.tsx
  frontend/src/components/admin/AdminPostingCard.tsx
  frontend/src/components/admin/schedule/AdminPostingScheduleHeader.tsx
  frontend/src/components/admin/schedule/AdminScheduleVolunteerRow.tsx
  frontend/src/components/admin/schedule/AdminScheduleVolunteerTable.tsx
  frontend/src/components/admin/schedule/ScheduleSidePanel.tsx
  frontend/src/components/pages/Default.tsx
  frontend/src/components/pages/admin/AdminHomepage.tsx
  frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
  frontend/src/types/PostingTypes.ts
  frontend/src/utils/DateTimeUtils.ts
  frontend/src/utils/TypeUtils.ts
Labels: ship it 🚢

#512 Admin homepage and wrap up everything except for edit posting
  backend/graphql/index.ts
  backend/graphql/resolvers/postingResolvers.ts
  backend/graphql/types/postingType.ts
  backend/services/implementations/postingService.ts
  backend/services/interfaces/postingService.ts
  backend/types.ts
  frontend/src/components/admin/AdminHomepageHeader.tsx
  frontend/src/components/admin/AdminPostingCard.tsx
  frontend/src/components/pages/Default.tsx
  frontend/src/components/pages/__tests__/Default.test.tsx
  frontend/src/components/pages/admin/AdminHomepage.tsx
  frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
  frontend/src/types/api/PostingTypes.ts
  frontend/src/utils/TypeUtils.ts
Labels: ship it 🚢

#520 added createdAt and updatedAt params to all models
  backend/prisma/migrations/20220720213853_added_created_at_and_updated_at_col_to_all_models/migration.sql
  backend/prisma/migrations/20220720214031_updated_updated_at_col_to_update_when_row_updates/migration.sql
  backend/prisma/schema.prisma
Labels: ship it 🚢

#518 Add edit posting page
  backend/graphql/resolvers/postingResolvers.ts
  backend/graphql/types/postingType.ts
  backend/prisma/migrations/20220723205401_add_cascade_delete_on_shift_signup/migration.sql
  backend/prisma/schema.prisma
  backend/services/implementations/postingService.ts
  backend/services/implementations/shiftService.ts
  backend/services/interfaces/postingService.ts
  backend/types.ts
  backend/utilities/dateUtils.ts
  frontend/src/App.tsx
  frontend/src/components/admin/AdminPostingCard.tsx
  frontend/src/components/admin/posting/PostingFormBasicInfo.tsx
  frontend/src/components/admin/posting/PostingFormReview.tsx
  frontend/src/components/admin/posting/PostingFormShifts.tsx
  frontend/src/components/pages/admin/AdminHomepage.tsx
  frontend/src/components/pages/admin/posting/CreatePostingBasicInfoPage.tsx
  frontend/src/components/pages/admin/posting/CreatePostingPage.tsx
  frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
  frontend/src/components/pages/admin/posting/EditPostingPage.tsx
  frontend/src/components/pages/admin/posting/PostingFormBasicInfoPage.tsx
  frontend/src/components/pages/admin/posting/PostingFormReviewPage.tsx
  frontend/src/components/pages/admin/posting/PostingFormShiftsPage.tsx
  frontend/src/constants/Routes.ts
  frontend/src/types/api/PostingTypes.ts
Labels: awaiting review 👀

#522 Create Volunteer Profile Side Panel
  backend/prisma/seed.ts
  frontend/src/components/admin/schedule/AdminScheduleVolunteerRow.tsx
  frontend/src/components/admin/schedule/AdminScheduleVolunteerTable.tsx
  frontend/src/components/admin/schedule/ScheduleSidePanel.tsx
  frontend/src/components/admin/schedule/volunteersidepanel/NoVolunteerShiftsRow.tsx
  frontend/src/components/admin/schedule/volunteersidepanel/VolunteerNameHeader.tsx
  frontend/src/components/admin/schedule/volunteersidepanel/VolunteerShiftsRow.tsx
  frontend/src/components/admin/schedule/volunteersidepanel/VolunteerShiftsTable.tsx
  frontend/src/components/admin/schedule/volunteersidepanel/VolunteerSidePanel.tsx
  frontend/src/components/admin/schedule/volunteersidepanel/VolunteerSkillsSection.tsx
  frontend/src/components/pages/admin/schedule/NoShiftsPanel.tsx
  frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
  frontend/src/types/api/ShiftSignupTypes.ts
  frontend/src/utils/DateTimeUtils.ts
Labels: ship it 🚢

#517 User Account Creation Flow
  backend/graphql/index.ts
  backend/graphql/resolvers/userResolvers.ts
  backend/graphql/types/userType.ts
  backend/package.json
  backend/services/implementations/userService.ts
  backend/services/interfaces/userService.ts
  backend/types.ts
  backend/utilities/dateUtils.ts
  backend/yarn.lock
  frontend/src/components/admin/AddAdminModal.tsx
  frontend/src/components/admin/AddVolunteerModal.tsx
  frontend/src/components/admin/AdminUserManagementPageHeader.tsx
  frontend/src/components/pages/CreateAccountPage.tsx
  frontend/src/components/pages/NewAccountPage.tsx
  frontend/src/components/user/AccountForm.tsx
  frontend/src/types/api/UserType.ts
Labels: ship it 🚢

#528 User Profile Panel
  frontend/src/components/admin/users/ProfileDrawer.tsx
  frontend/src/components/admin/users/UserManagementTableRow.tsx
  frontend/src/components/pages/admin/user/AdminUserManagementPage.tsx
Labels: ship it 🚢
