Repository uwblueprint/sistering, pull requests merged in 2022-08, with the labels that each got.

#541 Migrate DoB and pronouns to user model
  backend/graphql/types/userType.ts
  backend/prisma/migrations/20220731144814_made_do_b_and_pronouns_part_of_user/migration.sql
  backend/prisma/schema.prisma
  backend/prisma/seed.ts
  backend/services/implementations/__tests__/userService.test.ts
  backend/services/implementations/userService.ts
  backend/types.ts
  frontend/src/components/pages/EditAccountPage.tsx
  frontend/src/components/user/AccountForm.tsx
  frontend/src/types/api/EmployeeTypes.ts
  frontend/src/types/api/UserType.ts
Labels: ship it 🚢

#542 Link Sistering logo to user homepage :sparkles:
  frontend/src/components/common/Navbar.tsx
Labels: ship it 🚢

#545 Fixing Edit Account Header
  frontend/src/components/pages/EditAccountPage.tsx
Labels: ship it 🚢

#554 Add missing posting detail links to admin posting cards
  frontend/src/components/admin/AdminPostingCard.tsx
  frontend/src/components/pages/admin/AdminHomepage.tsx
  frontend/src/components/pages/admin/posting/AdminPostingDetails.tsx
Labels: ship it 🚢

#551 Remove unused routes
  backend/graphql/index.ts
  frontend/public/manifest.json
  frontend/src/App.tsx
  frontend/src/components/auth/Signup.tsx
  frontend/src/components/pages/EditTeamPage.tsx
  frontend/src/components/pages/HooksDemo/EmojiSection.tsx
  frontend/src/components/pages/HooksDemo/HooksDemo.tsx
  frontend/src/components/pages/HooksDemo/emojis.ts
  frontend/src/components/pages/HooksDemo/index.ts
  frontend/src/components/pages/HooksDemo/styles.css
  frontend/src/constants/Routes.ts
  frontend/src/contexts/SampleContext.ts
  frontend/src/contexts/SampleContextDispatcherContext.ts
  frontend/src/reducers/SampleContextReducer.ts
  frontend/src/types/SampleContextTypes.ts
Labels: ship it 🚢

#557 added emerg contact info in account form
  frontend/src/components/pages/EditAccountPage.tsx
  frontend/src/components/user/AccountForm.tsx
Labels: ship it 🚢

#548 added toast errors to all mutations
  frontend/src/components/admin/BranchManagerModal.tsx
  frontend/src/components/admin/BranchManagerTable.tsx
  frontend/src/components/admin/RemoveVolunteerModal.tsx
  frontend/src/components/auth/Login.tsx
  frontend/src/components/auth/Logout.tsx
  frontend/src/components/auth/RefreshCredentials.tsx
  frontend/src/components/auth/ResetPassword.tsx
  frontend/src/components/common/Navbar.tsx
  frontend/src/components/crud/CreateForm.tsx
  frontend/src/components/crud/UpdateForm.tsx
  frontend/src/components/pages/EditAccountPage.tsx
  frontend/src/components/pages/NewAccountPage.tsx
  frontend/src/components/pages/admin/AdminHomepage.tsx
  frontend/src/components/pages/admin/posting/PostingFormReviewPage.tsx
  frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
Labels: ship it 🚢

#525 Integrate User Invites Modal with Backend
  backend/graphql/index.ts
  backend/graphql/resolvers/userResolvers.ts
  backend/graphql/types/userType.ts
  backend/services/implementations/userService.ts
  backend/services/interfaces/userService.ts
  backend/types.ts
  frontend/src/components/admin/UserInvitesModal.tsx
  frontend/src/components/admin/UserInvitesTable.tsx
  frontend/src/types/api/UserInviteTypes.ts
Labels: ship it 🚢

#581 Remove all uses of sendEmailVerificationLink method
  backend/graphql/resolvers/authResolvers.ts
  backend/graphql/resolvers/userResolvers.ts
  backend/services/implementations/authService.ts
  backend/services/interfaces/authService.ts
Labels: ship it 🚢

#579 Clear posting context before visiting new create or edit posting pages
  frontend/src/components/admin/AdminHomepageHeader.tsx
  frontend/src/components/pages/admin/AdminHomepage.tsx
  frontend/src/reducers/PostingContextReducer.ts
  frontend/src/types/PostingContextTypes.ts
Labels: ship it 🚢

#580 Remove user panel mutation + fix panel UI overflow
  backend/prisma/migrations/20220811201841_delete_user_cascade_signups/migration.sql
  backend/prisma/schema.prisma
  frontend/src/components/admin/users/ProfileDrawer.tsx
Labels: ship it 🚢

#585 Use title case for languages in create/edit account form
  frontend/src/components/pages/EditAccountPage.tsx
  frontend/src/components/user/AccountForm.tsx
Labels: ship it 🚢

#586 Remove unused admin reset user password button
  frontend/src/components/admin/users/ProfileDrawer.tsx
Labels: ship it 🚢

#547 Add schedule flow toasts and closed posting state
  frontend/package.json
  frontend/src/components/admin/BranchManagerTable.tsx
  frontend/src/components/admin/posting/PostingFormBasicInfo.tsx
  frontend/src/components/admin/schedule/AdminPostingScheduleHeader.tsx
  frontend/src/components/admin/schedule/AdminScheduleVolunteerTable.tsx
  frontend/src/components/admin/schedule/ScheduleSidePanel.tsx
  frontend/src/components/common/StickyBackNext.tsx
  frontend/src/components/pages/AccountCreatedPage.tsx
  frontend/src/components/pages/EditAccountPage.tsx
  frontend/src/components/pages/NewAccountPage.tsx
  frontend/src/components/pages/admin/posting/PostingFormReviewPage.tsx
  frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
  frontend/yarn.lock
Labels: ship it 🚢

#587 Add clickable logo on signup nav and customize tabs on edit-account ✨
  frontend/src/components/common/SignupNavbar.tsx
  frontend/src/components/pages/EditAccountPage.tsx
Labels: ship it 🚢

#578 Remove shift creation start date guard for backend handling
  backend/services/implementations/shiftService.ts
  frontend/src/components/admin/ShiftCalendar/WeekViewShiftCalendar.tsx
Labels: ship it 🚢

#584 Implement Organization-Wide Calendar for Admins & Employees
  backend/graphql/index.ts
  backend/graphql/resolvers/postingResolvers.ts
  backend/graphql/resolvers/shiftResolvers.ts
  backend/graphql/types/shiftType.ts
  backend/services/implementations/postingService.ts
  backend/services/implementations/shiftService.ts
  backend/services/interfaces/shiftService.ts
  frontend/src/App.tsx
  frontend/src/components/admin/AdminHomepageHeader.tsx
  frontend/src/components/admin/ShiftCalendar/MonthViewShiftCalendar.tsx
  frontend/src/components/admin/calendar/OrgWideCalendar.tsx
  frontend/src/constants/Routes.ts
  frontend/src/types/api/ShiftTypes.ts
Labels: ship it 🚢

#538 Remove unused profile photo upload button + text
  frontend/src/components/pages/EditAccountPage.tsx
  frontend/src/components/pages/NewAccountPage.tsx
  frontend/src/components/user/AccountForm.tsx
  frontend/src/components/user/ProfilePhotoForm.tsx
Labels: ship it 🚢

#546 Remove backend logout call on refresh failure and reload window
  frontend/src/App.tsx
  frontend/src/index.tsx
Labels: ship it 🚢

#605 Change textbox width
  frontend/src/components/common/RichText/RichTextField.tsx
Labels: ship it 🚢

#601 Add unavailable shifts tab to volunteer shifts table
  frontend/src/components/admin/ShiftCalendar/MonthlyViewReadOnlyShiftCalendar.tsx
  frontend/src/components/admin/calendar/OrgWideCalendar.tsx
  frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
  frontend/src/components/volunteer/shifts/VolunteerShiftsTable.tsx
  frontend/src/theme/index.ts
Labels: ship it 🚢

#589 Fixed non aligned tags in account forms
  frontend/src/components/user/AccountForm.tsx
Labels: ship it 🚢

#608 Add branch tags to edit profile page
  frontend/src/components/pages/EditAccountPage.tsx
Labels: ship it 🚢

#598 Update branch mutation query to remove stale signups + unsaved selected branches bug
  backend/services/implementations/branchService.ts
  frontend/src/components/admin/users/ProfileDrawer.tsx
  frontend/src/components/admin/users/UserManagementTableProfileCell.tsx
  frontend/src/components/pages/admin/user/MultiBranchSelector.tsx
Labels: ship it 🚢

#597 Remove unused posting review page route
  frontend/src/App.tsx
  frontend/src/components/pages/admin/schedule/AdminSchedulePostingReviewPage.tsx
  frontend/src/constants/Routes.ts
Labels: ship it 🚢

#607 Update 404 page
  frontend/src/assets/Sistering_frown.svg
  frontend/src/components/pages/NotFound.tsx
Labels: ship it 🚢

#596 Skill +x tag and plural posting card bug fixes
  frontend/src/components/admin/AdminPostingCard.tsx
  frontend/src/components/admin/posting/PostingFormBasicInfo.tsx
  frontend/src/components/admin/schedule/volunteersidepanel/VolunteerSkillsSection.tsx
  frontend/src/components/admin/users/ProfileDrawer.tsx
  frontend/src/components/common/TagsPopover.tsx
  frontend/src/components/user/fields/SelectorField.tsx
Labels: ship it 🚢

#609 Update getShiftSignupForUser to only return signups for current postings
  backend/services/implementations/postingService.ts
  backend/services/implementations/shiftSignupService.ts
  backend/utilities/dateUtils.ts
Labels: ship it 🚢

#622 Fix timezone bug in VolunteerPendingShiftsTableRow
  frontend/src/utils/DateTimeUtils.ts
Labels: ship it 🚢

#611 Set unselected signups to cancelled on posting publish
  frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
Labels: ship it 🚢

#628 Fix page overflow on Admin Schedule Review Page
  frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
Labels: ship it 🚢

#627 Reword Volunteer Shifts Tab to be Less Vague + UI underflow
  frontend/src/components/admin/BranchManagerTable.tsx
  frontend/src/components/admin/LanguageManagerTable.tsx
  frontend/src/components/admin/SkillsManagerTable.tsx
  frontend/src/components/auth/Login.tsx
  frontend/src/components/auth/ResetPassword.tsx
  frontend/src/components/common/Loading.tsx
  frontend/src/components/pages/AccountCreatedPage.tsx
  frontend/src/components/pages/CreateAccountPage.tsx
  frontend/src/components/pages/NotFound.tsx
  frontend/src/components/pages/admin/AdminHomepage.tsx
  frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
  frontend/src/components/pages/admin/user/AdminUserManagementPage.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
  frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx
  frontend/src/components/volunteer/shifts/VolunteerShiftsTable.tsx
  frontend/src/components/volunteer/shifts/VolunteerShiftsTableEmptyState.tsx
Labels: awaiting review 👀, ship it 🚢

#636 Fix create-account page continue link attach to button
  frontend/src/components/pages/CreateAccountPage.tsx
Labels: ship it 🚢

#635 Fix admin posting card event date range
  frontend/src/components/admin/AdminPostingCard.tsx
Labels: ship it 🚢

#641 Add a refetch query to admin invite mutation :sparkles:
  frontend/src/components/admin/AddAdminModal.tsx
  frontend/src/components/admin/AddVolunteerModal.tsx
Labels: ship it 🚢

#646 Update seed, fix tag overflow issues
  backend/prisma/seed.ts
  frontend/src/components/admin/BranchManagerTable.tsx
  frontend/src/components/common/OverflownText.tsx
  frontend/src/components/pages/admin/user/MultiBranchSelector.tsx
Labels: ship it 🚢

#637 Only show volunteer posting details if user in branch
  backend/graphql/resolvers/postingResolvers.ts
  backend/services/implementations/postingService.ts
  backend/services/interfaces/postingService.ts
  frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
Labels: ship it 🚢

#633 Fix datetime utils to account for timezone interaction
  frontend/src/components/admin/UserInvitesTable.tsx
  frontend/src/components/admin/posting/PostingFormShifts.tsx
  frontend/src/components/admin/schedule/ShiftTimeHeader.tsx
  frontend/src/components/admin/schedule/VolunteerProfileShiftRow.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
  frontend/src/components/volunteer/PostingCard.tsx
  frontend/src/components/volunteer/shifts/VolunteerAvailabilityTableRow.tsx
  frontend/src/components/volunteer/shifts/VolunteerShiftsTable.tsx
  frontend/src/components/volunteer/shifts/VolunteerUpcomingShiftsTableRow.tsx
  frontend/src/utils/DateTimeUtils.ts
Labels: awaiting review 👀

#639 Update navbar logout to manually clear auth token and refresh
  frontend/src/APIClients/AuthAPIClient.ts
  frontend/src/components/auth/Logout.tsx
  frontend/src/components/common/Navbar.tsx
  frontend/src/index.tsx
Labels: awaiting review 👀

#638 Update weekly calendar view to restrict invalid start
  frontend/src/components/admin/ShiftCalendar/WeekViewShiftCalendar.tsx
  frontend/src/components/admin/posting/PostingFormShifts.tsx
Labels: changes requested 📝

#640 Update better toast msg of delete branch failure toast
  frontend/src/components/admin/BranchManagerTable.tsx
Labels: changes requested 📝

#648 Add firebase hosting prod deploy workflow
  .github/workflows/firebase-hosting-merge-prod.yml
Labels: awaiting review 👀

#649 Fix employees can see postings outside of branch
  backend/graphql/resolvers/branchResolvers.ts
  backend/graphql/resolvers/postingResolvers.ts
  backend/graphql/types/postingType.ts
  backend/services/implementations/branchService.ts
  backend/services/implementations/postingService.ts
  backend/services/interfaces/branchService.ts
  backend/services/interfaces/postingService.ts
  backend/utilities/dateUtils.ts
  frontend/src/components/admin/calendar/OrgWideCalendar.tsx
  frontend/src/components/pages/admin/posting/AdminPostingDetails.tsx
  frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
Labels: ship it 🚢

#651 Add missing navbars to pages
  frontend/src/components/admin/AdminHomepageHeader.tsx
  frontend/src/components/admin/AdminUserManagementPageHeader.tsx
  frontend/src/components/pages/AccountCreatedPage.tsx
  frontend/src/components/pages/CreateAccountPage.tsx
  frontend/src/components/pages/CreatePage.tsx
  frontend/src/components/pages/DisplayPage.tsx
  frontend/src/components/pages/UpdatePage.tsx
  frontend/src/components/pages/admin/posting/AdminPostingDetails.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
Labels: awaiting review 👀

#667 Update languages field to use SearchSelectorField
  backend/graphql/index.ts
  frontend/src/components/user/AccountForm.tsx
  frontend/src/components/user/fields/SearchSelectorField.tsx
Labels: ship it 🚢

#665 Fix update user resolver to exclude branches as it is only changed by super admin via other resolvers
  backend/graphql/types/userType.ts
  backend/services/implementations/userService.ts
  backend/types.ts
  frontend/src/components/user/AccountForm.tsx
  frontend/src/types/api/UserType.ts
Labels: awaiting review 👀
