Repository uwblueprint/sistering, pull requests merged in 2022-04, with the labels that each got.

#206 Create admin schedule review table
  frontend/src/components/admin/schedule/AdminScheduleTable.tsx
  frontend/src/components/admin/schedule/AdminScheduleTableDate.tsx
  frontend/src/components/admin/schedule/AdminScheduleTableRow.tsx
  frontend/src/theme/colors.ts
Labels: ship it 🚢

#249 Add posting fields to shiftSignup fetch
  backend/graphql/index.ts
  backend/graphql/types/shiftSignupType.ts
  backend/services/implementations/shiftSignupService.ts
  backend/types.ts
Labels: ship it 🚢

#238 Add Rich Text Field for Create Posting Basic Info
  frontend/src/assets/RichTextField/B.svg
  frontend/src/assets/RichTextField/I.svg
  frontend/src/assets/RichTextField/U.svg
  frontend/src/assets/RichTextField/ordered-list.svg
  frontend/src/assets/RichTextField/unordered-list.svg
  frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx
  frontend/src/components/common/RichTextField.tsx
Labels: ship it 🚢

#246 Add Edit Volunteer Row
  frontend/src/assets/Person_Icon.svg
  frontend/src/components/admin/schedule/AdminScheduleVolunteerRow.tsx
Labels: ship it 🚢

#226 Schedule creation page header
  frontend/src/components/admin/schedule/AdminSchedulePageHeader.tsx
Labels: ship it 🚢

#252 No shifts panel
  frontend/src/components/pages/admin/schedule/NoShiftsPanel.tsx
  frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx
  frontend/src/constants/Copy.ts
Labels: changes requested 📝

#251 Edit volunteers shift time header
  frontend/src/components/admin/schedule/ShiftTimeHeader.tsx
Labels: ship it 🚢

#260 Allow RichTextDisplay to handle font-sizes
  frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx
  frontend/src/components/common/RichText/RichTextDisplay.tsx
  frontend/src/components/common/RichText/RichTextField.tsx
  frontend/src/components/common/RichText/fontSizeObject.ts
Labels: ship it 🚢

#225 Create volunteer shifts table
  frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx
  frontend/src/components/volunteer/shifts/VolunteerShiftsTable.tsx
  frontend/src/components/volunteer/shifts/VolunteerShiftsTableDate.tsx
  frontend/src/components/volunteer/shifts/VolunteerShiftsTableRow.tsx
  frontend/src/theme/index.ts
  frontend/src/types/api/ShiftSignupTypes.ts
  frontend/src/utils/DateTimeUtils.ts
Labels: ship it 🚢

#262 Link posting cards to details and submit availabilities pages
  frontend/src/components/common/PostingDetails.tsx
  frontend/src/components/pages/admin/posting/AdminPostingDetails.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
  frontend/src/components/volunteer/PostingCard.tsx
Labels: ship it 🚢

#263 Augment Employee Model
  backend/graphql/types/postingType.ts
  backend/graphql/types/userType.ts
  backend/prisma/migrations/20220408003859_update/migration.sql
  backend/prisma/schema.prisma
  backend/prisma/seed.ts
  backend/services/implementations/postingService.ts
  backend/services/implementations/userService.ts
  backend/types.ts
  frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx
  frontend/src/components/admin/posting/CreatePostingReview.tsx
  frontend/src/types/api/EmployeeTypes.ts
Labels: ship it 🚢

#268 Implement edit volunteers panel body
  frontend/src/components/admin/schedule/AdminScheduleVolunteerRow.tsx
  frontend/src/components/admin/schedule/AdminScheduleVolunteerTable.tsx
  frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
  frontend/src/theme/index.ts
  frontend/src/types/api/SignupTypes.ts
Labels: ship it 🚢

#273 Create shifts with posting
  backend/graphql/resolvers/postingResolvers.ts
  backend/graphql/types/postingType.ts
  backend/services/implementations/postingService.ts
  backend/services/implementations/shiftService.ts
  backend/services/interfaces/IShiftService.ts
  backend/services/interfaces/postingService.ts
  backend/types.ts
  frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
  frontend/src/types/api/PostingTypes.ts
Labels: ship it 🚢

#261 Load initial create posting values from context
  frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx
  frontend/src/components/admin/posting/CreatePostingShifts.tsx
  frontend/src/contexts/admin/PostingContext.ts
  frontend/src/types/PostingContextTypes.ts
Labels: awaiting review 👀

#253 Add submit signups mutation to availability page
  backend/graphql/index.ts
  backend/graphql/resolvers/shiftSignupResolvers.ts
  backend/graphql/types/shiftSignupType.ts
  backend/services/implementations/shiftSignupService.ts
  backend/services/interfaces/shiftSignupService.ts
  backend/types.ts
  frontend/src/types/api/SignupTypes.ts
Labels: ship it 🚢

#274 Add Optional Query Parameters to Postings Query
  backend/graphql/index.ts
  backend/graphql/resolvers/postingResolvers.ts
  backend/graphql/types/postingType.ts
  backend/services/implementations/postingService.ts
  backend/services/interfaces/postingService.ts
  frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
Labels: ship it 🚢

#259 Schedule Review Table Data Fetch
  backend/graphql/index.ts
  backend/graphql/resolvers/shiftResolvers.ts
  backend/graphql/types/shiftSignupType.ts
  backend/graphql/types/shiftType.ts
  backend/graphql/types/userType.ts
  backend/services/implementations/shiftService.ts
  backend/services/implementations/userService.ts
  backend/services/interfaces/IShiftService.ts
  backend/types.ts
  frontend/src/components/admin/schedule/AdminScheduleTable.tsx
  frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
  frontend/src/types/api/ShiftTypes.ts
  frontend/src/types/api/SignupTypes.ts
  frontend/src/types/api/UserType.ts
Labels: ship it 🚢

#266 Admin Posting Schedule Header
  frontend/src/App.tsx
  frontend/src/components/admin/schedule/AdminPostingScheduleHeader.tsx
  frontend/src/components/pages/admin/schedule/AdminSchedulePostingReviewPage.tsx
  frontend/src/constants/Routes.ts
Labels: ship it 🚢

#267 Redirect to posting details page and display success toast upon submitting availability
  frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
Labels: ship it 🚢

#293 Update default numVolunteers to 1 in default posting context
  frontend/src/contexts/admin/PostingContext.ts
Labels: ship it 🚢

#286 Set up admin schedule layout
  frontend/src/components/admin/ShiftCalendar/MonthlyViewReadOnlyShiftCalendar.tsx
  frontend/src/components/admin/schedule/AdminPostingScheduleHeader.tsx
  frontend/src/components/admin/schedule/AdminSchedulePageHeader.tsx
  frontend/src/components/admin/schedule/AdminScheduleTable.tsx
  frontend/src/components/admin/schedule/AdminScheduleTableRow.tsx
  frontend/src/components/admin/schedule/ShiftTimeHeader.tsx
  frontend/src/components/common/Navbar.tsx
  frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
  frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx
  frontend/src/constants/Routes.ts
  frontend/src/constants/Tabs.ts
  frontend/src/constants/Volunteer.ts
Labels: ship it 🚢

#292 Error modal
  frontend/src/components/auth/Login.tsx
  frontend/src/components/auth/ResetPassword.tsx
  frontend/src/components/common/ErrorModal.tsx
  frontend/src/components/pages/admin/posting/AdminPostingDetails.tsx
  frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
  frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
  frontend/src/components/pages/admin/schedule/AdminSchedulePostingReviewPage.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
  frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
  frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx
Labels: ship it 🚢

#295 Fix num volunteers input for admin posting flow NaN bug
  frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx
Labels: ship it 🚢

#278 Side panel
  frontend/package.json
  frontend/src/components/admin/schedule/AdminScheduleVolunteerRow.tsx
  frontend/src/components/admin/schedule/AdminScheduleVolunteerTable.tsx
  frontend/src/components/admin/schedule/ScheduleSidePanel.tsx
  frontend/src/components/admin/schedule/ShiftTimeHeader.tsx
  frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
  frontend/src/components/pages/admin/schedule/testData.ts
  frontend/yarn.lock
Labels: ship it 🚢
